language: php

notifications:
  email:
    on_success: never

git:
  depth: 2

matrix:
  include:
    - php: 7.1
    - php: 7.2
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo # Rapid composer installation
  - travis_retry composer install --no-interaction
  - >
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter &&
    chmod +x ./cc-test-reporter &&
    ./cc-test-reporter before-build

script:
  - composer format-preview
  - composer test-in-ci

after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
